version: '3.9'

services:
  client:
    build:
      context: .
      dockerfile: src/main/resources/library.dockerfile
    expose:
      - 8080
    ports:
      - "8080:8080"
    networks:
      - network1
networks:
  network1:
    driver: bridge