version: '3.9'

services:
  legacy:
    build:
      context: legacy
      dockerfile: src/main/resources/library.dockerfile
    environment:
      NOTIFICATION_SERVICE_URL: http://notification:8080
    ports:
      - "8080:8080"
    networks:
      - network1
  notification:
    build:
      context: notification-service
      dockerfile: src/main/resources/notification.dockerfile
    expose:
      - 8080
    ports:
      - "8090:8080"
    networks:
      - network1
networks:
  network1:
    driver: bridge