spring:
  jpa:
    database: H2
    generate-ddl: true
legacy:
  notification: "${ENABLE_LEGACY: true}"
  order: true
  book: true
  delivery: true
  payment: true
notification:
    url: ${NOTIFICATION_SERVICE_URL:http://localhost:8070}/notifications
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      show-values: ALWAYS
