spring:
  jpa:
    database: H2
    generate-ddl: true
legacy:
  notification: "${ENABLE_LEGACY: true}"
  order: true
  book: true
  delivery: true
  payment: true
notification:
  service:
    url: ${NOTIFICATION_SERVICE_URL:http://localhost:8070}/notifications
